'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Clock3, LockKeyhole, PlayCircle, Star } from 'lucide-react';
import { useParams } from 'next/navigation';
import { PageShell } from '@/components/PageShell';
import { Protected } from '@/components/Protected';
import { getEpisodes, getMediaById } from '@/lib/content';
import { useApp } from '@/components/AppProvider';
import type { DramaEpisode, MediaItem } from '@/lib/types';

export default function DramaDetails(){
 const {isVip,profile}=useApp(); const params=useParams<{id:string}>(); const id=decodeURIComponent(params.id); const [drama,setDrama]=useState<MediaItem|null>(null); const [episodes,setEpisodes]=useState<DramaEpisode[]>([]);
 useEffect(()=>{getMediaById(id).then(setDrama).catch(()=>{});},[id]);
 useEffect(()=>{getEpisodes(id,isVip).then(setEpisodes).catch(()=>setEpisodes([]));},[id,isVip]);
 const seasons=useMemo(()=>Array.from(new Set(episodes.map(e=>e.seasonNumber))).sort((a,b)=>a-b),[episodes]);
 return <PageShell><Protected>{drama?.type==='drama'?<div className="max-w-6xl mx-auto space-y-7"><Link href="/drama" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16}/> {`Drama`}</Link><section className="glass rounded-[2rem] overflow-hidden"><div className="grid lg:grid-cols-[280px_1fr] gap-0"><div className="aspect-[2/3] lg:aspect-auto bg-slate-900"><img src={drama.poster} alt={drama.title} className="w-full h-full object-cover"/></div><div className="p-6 sm:p-9 flex flex-col justify-center"><div className="flex items-center gap-2 text-violet-300 text-xs font-black uppercase tracking-widest"><span>{drama.year}</span><span>•</span><span>{drama.genre}</span>{drama.accessLevel==='vip'&&<span className="inline-flex items-center gap-1 rounded-full bg-violet-500/15 px-2 py-1"><LockKeyhole size={12}/> VIP</span>}</div><h1 className="text-4xl sm:text-5xl font-black mt-3">{drama.title}</h1><p className="text-slate-400 leading-7 mt-4 max-w-2xl">{drama.description}</p><div className="mt-6 flex flex-wrap gap-2"><span className="glass rounded-full px-3 py-2 text-xs font-bold">{episodes.length} Episodes</span><span className="glass rounded-full px-3 py-2 text-xs font-bold">{isVip?'VIP access':'Free access'}</span></div></div></div></section>{seasons.map(season=><section key={season} className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Season {season}</h2><span className="text-xs text-slate-500">{episodes.filter(e=>e.seasonNumber===season).length} episodes</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{episodes.filter(e=>e.seasonNumber===season).map(ep=><Link key={ep.id} href={`/watch?episode=${encodeURIComponent(ep.id)}`} className="glass rounded-2xl p-4 flex items-center gap-3 hover:bg-white/[.07] transition"><span className="h-11 w-11 rounded-xl bg-violet-500/10 text-violet-300 grid place-items-center font-black">{String(ep.episodeNumber).padStart(2,'0')}</span><div className="min-w-0 flex-1"><div className="font-bold truncate">{ep.title}</div><div className="text-xs text-slate-500 mt-1 flex items-center gap-2"><Clock3 size={12}/>{ep.durationMinutes?`${ep.durationMinutes} min`:'Episode'}{ep.accessLevel==='vip'&&<><span>•</span><span className="text-violet-300">VIP</span></>}</div></div><PlayCircle size={20} className="text-slate-400"/></Link>)}</div></section>)}{!episodes.length&&<div className="glass rounded-2xl p-10 text-center text-slate-500">No episodes are available for this access level yet.</div>}</div>:<div className="min-h-[60vh] grid place-items-center text-slate-500">Drama not found.</div>}</Protected></PageShell>
}
